# Sample logging file.
# Ideas stolen from:
# http://victorlin.me/posts/2012/08/26/good-logging-practice-in-python
#
version: 1
disable_existing_loggers: 0
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    file_handler:
        class: seaice.logging.logging.GzipRotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: /share/logs/seaice/package-name.log
        maxBytes: 10485760 # 10MB
        backupCount: 1
        encoding: utf8

loggers:
    package-name:
        level: INFO
        handlers: [file_handler, console]
        propagate: False

root:
    level: INFO
    handlers: [file_handler, console]
