data_store: /share/apps/seaice/datastore/daily.p

output_file: asina_S_iqr_timeseries.png

hemi: S

month_bounds: [-3, 1]

plot_mean: false
plot_stdev: false

plot_median: true
plot_iqr: true
plot_idr: true

years:
  record_high_year:
    dash: 8px
  years_before_4:
    color: rgb(166, 9, 172)
  years_before_3:
    color: rgb(177, 89, 40)
  years_before_2:
    color: rgb(255, 127, 0)
  years_before_1:
    color: rgb(3, 88, 38)
  current:
    color: rgb(0, 152, 244)
